icons_format = "{icon}"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"

[block.format]
full = " $title.str(max_w:30) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:' %a %Y-%m-%d %R') "

[[block]]
block = "temperature"
interval = 10
format = " $icon $min min, $max max, $average avg"
chip = "*-isa-*"

[[block]]
block = "menu"
text = "\uf011"

[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"

[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"


# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# OneDark by Lalit Magant (http://github.com/tilal6991)

[theme]
theme = "gruvbox-dark"

# [theme.overrides]
# idle_bg = "#282c34"
# idle_fg = "#abb2bf"
# info_bg = "#56b6c2"
# info_fg = "#282c34"
# good_bg = "#98c379"
# good_fg = "#282c34"
# warning_bg = "#e5c07b"
# warning_fg = "#282c34"
# critical_bg = "#e06c75"
# critical_fg = "#282c34"
# # The rest of the theme settings are left at default.
